# Generated by Django 3.2.9 on 2021-12-08 06:02

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taxiApp', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.AddField(
            model_name='booking',
            name='depart_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='depart_time',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
    ]
