# Generated by Django 3.2.9 on 2021-12-08 06:27

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taxiApp', '0003_auto_20211208_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='depart_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Depart Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='depart_time',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Depart Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dropoff',
            field=models.CharField(max_length=350, verbose_name='Drop Off'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup',
            field=models.CharField(max_length=350, verbose_name='Pick Up'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fullname',
            field=models.CharField(max_length=120, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'received'), (2, 'replied'), (3, 'closed')], default=1),
        ),
    ]
