# Generated by Django 3.2.9 on 2021-12-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiApp', '0003_auto_20211129_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('accepted', 'accepted'), ('cancelled', 'cancelled')], max_length=85),
        ),
    ]
