# Generated by Django 3.2.9 on 2021-12-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiApp', '0004_auto_20211206_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Ok'), (4, 'Good'), (5, 'Outstanding')], default=3),
        ),
    ]
